name: Publish QMod

env:
  qmodName: Thicc_Saber

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true

    - name: Get Tag Version
      id: get_tag_version
      run: |
        echo ${GITHUB_REF#refs/tags/}
        echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    # Then, we want to use the commit we have just made, and force push our tag to that commit
    - name: Get Commit ID
      id: get_commit_id
      run: |
        echo `git rev-parse HEAD`
        echo ::set-output name=ID::`git rev-parse HEAD`

    - name: Force create tag
      run: |
        git tag --force ${{ steps.get_tag_version.outputs.TAG }} ${{ steps.get_commid_id.outputs.ID }}
    # Then, push, upload our artifacts, modify the config file to have soLink and debugSoLink

    - name: Create and push version specific branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git branch version-${{ steps.get_tag_version.outputs.TAG }}
        git push -u origin version-${{ steps.get_tag_version.outputs.TAG }} --force --tags

    # Get release that was created for this tag
    - name: Get Release
      uses: octokit/request-action@v2.x
      id: get_release
      with:
        route: GET /repos/:repository/releases/tags/${{ steps.get_tag_version.outputs.TAG }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release Upload URL
      id: get_upload_url
      run: |
        url=$(echo "$response" | jq -r '.upload_url')
        echo $url
        echo "::set-output name=upload_url::$url"
      env:
        response:  ${{ steps.get_release.outputs.data }}

    - name: Build Qmod
      run: |
        pwsh -Command ./buildQMOD.ps1

    - name: Upload Qmod Asset
      id: upload_qmod_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
        asset_path: ./ThiccSaber_v1.0.0.qmod
        asset_name: ${{env.qmodName}}-v${{ steps.get_tag_version.outputs.VERSION }}.qmod
        asset_content_type: application/octet-stream

    - name: Upload QMod to Mod Repo
      uses: BobbyShmurner/mod-uploader@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.REPO_TOKEN }}
        qmod-name: ${{env.qmodName}}-v${{ steps.get_tag_version.outputs.VERSION }}.qmod
        tag: ${GITHUB_REF#refs/tags/}
